sudo: false
language: c
addons:
    apt:
        packages:
            - libxcb1-dev
            - libxcb-util0-dev
            - libxcb-icccm4-dev
            - xcb-proto
            - libxcb-ewmh1-dev
            - libxcb-randr0-dev
compiler:
    - clang
    - gcc
script: make debug
notifications:
    irc:
        channels:
            - "irc.freenode.org#howm"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: never
    email: false
