language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxcb1-dev
    - sudo apt-get install -y libxcb-util0-dev
    - sudo apt-get install -y libxcb-icccm4-dev
    - sudo apt-get install -y libxcb-ewmh1-dev
    - sudo apt-get install -y xcb-proto
before_script:
    - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
    - wget https://github.com/torvalds/linux/blob/master/scripts/spelling.txt
    - chmod +x checkpatch.pl
script: make debug && make check
notifications:
    irc:
        channels:
            - "irc.freenode.org#howm"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: never
