language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxcb-keysyms1-dev
    - sudo apt-get install -y libxcb1-dev
    - sudo apt-get install -y libxcb-util0-dev
    - sudo apt-get install -y libxcb-icccm4-dev
    - sudo apt-get install -y libxcb-ewmh1-dev
    - sudo apt-get install -y xcb-proto
script: make debug
notifications:
    irc: "irc.freenode.net#howm"
