.TH "Arg" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arg \- 
.PP
Represents an argument\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char *const *const \fBcmd\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an argument\&. 

Used to hold data that is sent as a parameter to a function when called as a result of a keypress\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* const* const Arg::cmd"
Represents a command that will be called by a shell\&. 
.SS "int Arg::i"
Usually used for specifying workspaces or clients\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
