.TH "Client" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- 
.PP
Represents a client that is being handled by howm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBClient\fP * \fBnext\fP"
.br
.ti -1c
.RI "bool \fBis_fullscreen\fP"
.br
.ti -1c
.RI "bool \fBis_floating\fP"
.br
.ti -1c
.RI "bool \fBis_transient\fP"
.br
.ti -1c
.RI "bool \fBis_urgent\fP"
.br
.ti -1c
.RI "xcb_window_t \fBwin\fP"
.br
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.ti -1c
.RI "uint16_t \fBw\fP"
.br
.ti -1c
.RI "uint16_t \fBh\fP"
.br
.ti -1c
.RI "uint16_t \fBgap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a client that is being handled by howm\&. 

All the attributes that are needed by howm for a client are stored here\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t Client::gap"
The size of the useless gap between this client and the others\&. 
.SS "uint16_t Client::h"
The height of the client\&. 
.SS "bool Client::is_floating"
Is the client floating? 
.SS "bool Client::is_fullscreen"
Is the client fullscreen? 
.SS "bool Client::is_transient"
Is the client transient? Defined at: http://standards.freedesktop.org/wm-spec/wm-spec-latest.html 
.SS "bool Client::is_urgent"
This is set by a client that wants focus for some reason\&. 
.SS "struct \fBClient\fP* Client::next"
Clients are stored in a linked list- this represents the client after this one\&. 
.SS "uint16_t Client::w"
The width of the client\&. 
.SS "xcb_window_t Client::win"
The window that this client represents\&. 
.SS "uint16_t Client::x"
The x coordinate of the client\&. 
.SS "uint16_t Client::y"
The y coordinate of the client\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
