.TH "Command" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "void(* \fBfunc\fP )(const \fBArg\fP *)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* Command::func)(const \fBArg\fP *)"
The function to be called when a command comes in from the socket\&. 
.SS "char* Command::name"
The function's name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
