.TH "config.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'command\&.h'\fP
.br
\fC#include 'layout\&.h'\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'workspace\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_ENABLE\fP   false"
.br
.ti -1c
.RI "#define \fBLOG_LEVEL\fP   \fBLOG_DEBUG\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBRule\fP \fBrules\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG_ENABLE   false"
Enable debugging output 
.SS "#define LOG_LEVEL   \fBLOG_DEBUG\fP"
How much detail should be logged\&. A LOG_LEVEL of INFO will log almost everything, LOG_WARN will log warnings and errors and LOG_ERR will log only errors\&.
.PP
LOG_NONE means nothing will be logged\&.
.PP
LOG_DEBUG should be used by developers\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBRule\fP rules[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
        
        {"dwb", 3, false, false, false},
        {"mpv", 5, false, false, false}
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
