.TH "config" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <howm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfocus_mouse\fP"
.br
.ti -1c
.RI "bool \fBfocus_mouse_click\fP"
.br
.ti -1c
.RI "bool \fBfollow_move\fP"
.br
.ti -1c
.RI "uint16_t \fBborder_px\fP"
.br
.ti -1c
.RI "uint32_t \fBborder_focus\fP"
.br
.ti -1c
.RI "uint32_t \fBborder_unfocus\fP"
.br
.ti -1c
.RI "uint32_t \fBborder_prev_focus\fP"
.br
.ti -1c
.RI "uint32_t \fBborder_urgent\fP"
.br
.ti -1c
.RI "bool \fBbar_bottom\fP"
.br
.ti -1c
.RI "uint16_t \fBbar_height\fP"
.br
.ti -1c
.RI "uint16_t \fBop_gap_size\fP"
.br
.ti -1c
.RI "bool \fBcenter_floating\fP"
.br
.ti -1c
.RI "bool \fBzoom_gap\fP"
.br
.ti -1c
.RI "unsigned int \fBlog_level\fP"
.br
.ti -1c
.RI "uint16_t \fBfloat_spawn_width\fP"
.br
.ti -1c
.RI "uint16_t \fBfloat_spawn_height\fP"
.br
.ti -1c
.RI "unsigned int \fBdelete_register_size\fP"
.br
.ti -1c
.RI "uint16_t \fBscratchpad_height\fP"
.br
.ti -1c
.RI "uint16_t \fBscratchpad_width\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool config::bar_bottom"

.SS "uint16_t config::bar_height"

.SS "uint32_t config::border_focus"

.SS "uint32_t config::border_prev_focus"

.SS "uint16_t config::border_px"

.SS "uint32_t config::border_unfocus"

.SS "uint32_t config::border_urgent"

.SS "bool config::center_floating"

.SS "unsigned int config::delete_register_size"

.SS "uint16_t config::float_spawn_height"

.SS "uint16_t config::float_spawn_width"

.SS "bool config::focus_mouse"

.SS "bool config::focus_mouse_click"

.SS "bool config::follow_move"

.SS "unsigned int config::log_level"

.SS "uint16_t config::op_gap_size"

.SS "uint16_t config::scratchpad_height"

.SS "uint16_t config::scratchpad_width"

.SS "bool config::zoom_gap"


.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
