.TH "handler.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
handler.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandle_event\fP (xcb_generic_event_t *ev)"
.br
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void handle_event (xcb_generic_event_t *ev)"

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
