.TH "howm.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
howm.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
\fC#include <err\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <xcb/xcb_ewmh\&.h>\fP
.br
\fC#include 'op\&.h'\fP
.br
\fC#include 'command\&.h'\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBconfig\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWORKSPACES\fP   5"
.br
.ti -1c
.RI "#define \fBIPC_BUF_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBHOWM_PATH\fP   '/usr/bin/howm'"
.br
.ti -1c
.RI "#define \fBSOCK_PATH\fP   '/tmp/howm'"
.br
.ti -1c
.RI "#define \fBWS_DEF_LAYOUT\fP   \fBHSTACK\fP"
.br
.ti -1c
.RI "#define \fBMASTER_RATIO\fP   0\&.6"
.br
.ti -1c
.RI "#define \fBDEF_BORDER_FOCUS\fP   '#70898F'"
.br
.ti -1c
.RI "#define \fBDEF_BORDER_UNFOCUS\fP   '#55555'"
.br
.ti -1c
.RI "#define \fBDEF_BORDER_PREV_FOCUS\fP   '#74718E'"
.br
.ti -1c
.RI "#define \fBDEF_BORDER_URGENT\fP   '#FF0000'"
.br
.ti -1c
.RI "#define \fBGAP\fP   0"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstates\fP { \fBOPERATOR_STATE\fP, \fBCOUNT_STATE\fP, \fBMOTION_STATE\fP, \fBEND_STATE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhowm_info\fP (void)"
.br
.RI "\fIPrint debug information about the current state of howm\&. \fP"
.ti -1c
.RI "uint32_t \fBget_colour\fP (char *colour)"
.br
.RI "\fIConverts a hexcode colour into an X11 colourmap pixel\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBnumlockmask\fP"
.br
.ti -1c
.RI "int \fBretval\fP"
.br
.ti -1c
.RI "int \fBlast_ws\fP"
.br
.ti -1c
.RI "int \fBprevious_layout\fP"
.br
.ti -1c
.RI "int \fBcw\fP"
.br
.ti -1c
.RI "xcb_connection_t * \fBdpy\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_mode\fP"
.br
.ti -1c
.RI "uint16_t \fBscreen_height\fP"
.br
.ti -1c
.RI "uint16_t \fBscreen_width\fP"
.br
.ti -1c
.RI "int \fBcur_state\fP"
.br
.ti -1c
.RI "xcb_screen_t * \fBscreen\fP"
.br
.ti -1c
.RI "xcb_ewmh_connection_t * \fBewmh\fP"
.br
.ti -1c
.RI "bool \fBrunning\fP"
.br
.ti -1c
.RI "bool \fBrestart\fP"
.br
.ti -1c
.RI "\fBWorkspace\fP \fBwss\fP []"
.br
.ti -1c
.RI "struct \fBconfig\fP \fBconf\fP"
.br
.ti -1c
.RI "const char * \fBWM_ATOM_NAMES\fP []"
.br
.ti -1c
.RI "xcb_atom_t \fBwm_atoms\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define DEF_BORDER_FOCUS   '#70898F'"

.SS "#define DEF_BORDER_PREV_FOCUS   '#74718E'"

.SS "#define DEF_BORDER_UNFOCUS   '#55555'"

.SS "#define DEF_BORDER_URGENT   '#FF0000'"

.SS "#define GAP   0"

.SS "#define HOWM_PATH   '/usr/bin/howm'"

.SS "#define IPC_BUF_SIZE   1024"

.SS "#define MASTER_RATIO   0\&.6"

.SS "#define SOCK_PATH   '/tmp/howm'"

.SS "#define WORKSPACES   5"

.SS "#define WS_DEF_LAYOUT   \fBHSTACK\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstates\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOPERATOR_STATE \fP\fP
.TP
\fB\fICOUNT_STATE \fP\fP
.TP
\fB\fIMOTION_STATE \fP\fP
.TP
\fB\fIEND_STATE \fP\fP
.SH "Function Documentation"
.PP 
.SS "uint32_t get_colour (char *colour)"

.PP
Converts a hexcode colour into an X11 colourmap pixel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcolour\fP A string of the format '#RRGGBB', that will be interpreted as a colour code\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An X11 colourmap pixel\&. 
.RE
.PP

.SS "void howm_info (void)"

.PP
Print debug information about the current state of howm\&. This can be parsed by programs such as scripts that will pipe their input into a status bar\&. 
.SH "Variable Documentation"
.PP 
.SS "struct \fBconfig\fP conf"

.SS "unsigned int cur_mode"

.SS "int cur_state"

.SS "int cw"

.SS "xcb_connection_t* dpy"

.SS "xcb_ewmh_connection_t* ewmh"

.SS "int last_ws"

.SS "int numlockmask"

.SS "int previous_layout"

.SS "bool restart"

.SS "int retval"

.SS "bool running"

.SS "xcb_screen_t* screen"

.SS "uint16_t screen_height"

.SS "uint16_t screen_width"

.SS "const char* WM_ATOM_NAMES[]"

.SS "xcb_atom_t wm_atoms[]"

.SS "\fBWorkspace\fP wss[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
