.TH "Key" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Key \- 
.PP
Represents a key\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmod\fP"
.br
.ti -1c
.RI "unsigned int \fBmode\fP"
.br
.ti -1c
.RI "xcb_keysym_t \fBsym\fP"
.br
.ti -1c
.RI "void(* \fBfunc\fP )(const \fBArg\fP *)"
.br
.ti -1c
.RI "const \fBArg\fP \fBarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a key\&. 

Holds information relative to a key, such as keysym and the mode during which the keypress can be seen as valid\&. 
.SH "Member Data Documentation"
.PP 
.SS "const \fBArg\fP Key::arg"
The argument passed to the above function\&. 
.SS "void(* Key::func)(const \fBArg\fP *)"
The function to be called when this key is pressed\&. 
.SS "int Key::mod"
The mask of the modifiers pressed\&. 
.SS "unsigned int Key::mode"
The mode within which this keypress is valid\&. 
.SS "xcb_keysym_t Key::sym"
The keysym of the pressed key\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
