.TH "layout.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layout.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlayouts\fP { \fBZOOM\fP, \fBGRID\fP, \fBHSTACK\fP, \fBVSTACK\fP, \fBEND_LAYOUT\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBarrange_windows\fP (void)"
.br
.RI "\fICall the appropriate layout handler for each layout\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlayouts\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIZOOM \fP\fP
.TP
\fB\fIGRID \fP\fP
.TP
\fB\fIHSTACK \fP\fP
.TP
\fB\fIVSTACK \fP\fP
.TP
\fB\fIEND_LAYOUT \fP\fP
.SH "Function Documentation"
.PP 
.SS "void arrange_windows (void)"

.PP
Call the appropriate layout handler for each layout\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
