.TH "Motion" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Motion \- 
.PP
Represents a motion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmod\fP"
.br
.ti -1c
.RI "xcb_keysym_t \fBsym\fP"
.br
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a motion\&. 

A motion can be used to target an operation at something specific- such as a client or workspace\&.
.PP
For example:
.PP
q4c (Kill, 4, Clients)\&. 
.SH "Member Data Documentation"
.PP 
.SS "int Motion::mod"
The mask of the modifiers pressed\&. 
.SS "xcb_keysym_t Motion::sym"
The keysym of the pressed key\&. 
.SS "unsigned int Motion::type"
Represents whether the motion is for clients, WS etc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
