.TH "Operator" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Operator \- 
.PP
Represents an operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmod\fP"
.br
.ti -1c
.RI "xcb_keysym_t \fBsym\fP"
.br
.ti -1c
.RI "unsigned int \fBmode\fP"
.br
.ti -1c
.RI "void(* \fBfunc\fP )(const unsigned int type, const int cnt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an operator\&. 

Operators perform an action upon one or more targets (identified by motions)\&. 
.SH "Member Data Documentation"
.PP 
.SS "void(* Operator::func)(const unsigned int type, const int cnt)"
The function to be called when the key is pressed\&. 
.SS "int Operator::mod"
The mask of the modifiers pressed\&. 
.SS "unsigned int Operator::mode"
The mode within which this keypress is valid\&. 
.SS "xcb_keysym_t Operator::sym"
The keysym of the pressed key\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
