.TH "replay_state" 3 "Thu Oct 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
replay_state \- 
.PP
Represents the last command (and its arguments) or the last combination of operator, count and motion (ocm)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <command\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBlast_op\fP )(const unsigned int type, int cnt)"
.br
.ti -1c
.RI "void(* \fBlast_cmd\fP )(const \fBArg\fP *arg)"
.br
.ti -1c
.RI "const \fBArg\fP * \fBlast_arg\fP"
.br
.ti -1c
.RI "unsigned int \fBlast_type\fP"
.br
.ti -1c
.RI "int \fBlast_cnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the last command (and its arguments) or the last combination of operator, count and motion (ocm)\&. 
.SH "Member Data Documentation"
.PP 
.SS "const \fBArg\fP* replay_state::last_arg"
The last argument, passed to the last command\&. 
.SS "void(* replay_state::last_cmd)(const \fBArg\fP *arg)"
The last command to be called\&. 
.SS "int replay_state::last_cnt"
The last count passed to the last operator function\&. 
.SS "void(* replay_state::last_op)(const unsigned int type, int cnt)"
The last operator to be called\&. 
.SS "unsigned int replay_state::last_type"
The value determine by the last motion (workspace, client etc)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
