.TH "Rule" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rule \- 
.PP
Represents a rule that is applied to a client upon it starting\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBclass\fP"
.br
.ti -1c
.RI "int \fBws\fP"
.br
.ti -1c
.RI "bool \fBfollow\fP"
.br
.ti -1c
.RI "bool \fBis_floating\fP"
.br
.ti -1c
.RI "bool \fBis_fullscreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a rule that is applied to a client upon it starting\&. 
.SH "Member Data Documentation"
.PP 
.SS "const char* Rule::class"
The class or name of the client\&. 
.SS "bool Rule::follow"
If the client is spawned on another ws, shall we follow? 
.SS "bool Rule::is_floating"
Spawn the client in a floating state? 
.SS "bool Rule::is_fullscreen"
Spawn the client in a fullscreen state? 
.SS "int Rule::ws"
The workspace that the client should be spawned on (0 means current workspace)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
