.TH "stack" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack \- 
.PP
Represents a stack\&. This stack is going to hold linked lists of clients\&. An example of the stack is below:  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scratchpad\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "\fBClient\fP ** \fBcontents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a stack\&. This stack is going to hold linked lists of clients\&. An example of the stack is below: 


.SH "TOP "
.PP
.PP
.SH "c1->c2->c3->NULL "
.PP
.PP
.SH "c1->NULL "
.PP
.PP
.SH "c1->c2->c3->NULL "
.PP
.PP
BOTTOM 
.SH "Member Data Documentation"
.PP 
.SS "\fBClient\fP** stack::contents"
The contents is an array of linked lists\&. Storage is malloced later as we don't know the size yet\&. 
.SS "unsigned int stack::size"
The amount of items in the stack\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
