.TH "types.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
types.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <xcb/xcb\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRule\fP"
.br
.RI "\fIRepresents a rule that is applied to a client upon it starting\&. \fP"
.ti -1c
.RI "struct \fBClient\fP"
.br
.RI "\fIRepresents a client that is being handled by howm\&. \fP"
.ti -1c
.RI "struct \fBWorkspace\fP"
.br
.RI "\fIRepresents a workspace, which stores clients\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBClient\fP \fBClient\fP"
.br
.RI "\fIRepresents a client that is being handled by howm\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBClient\fP  \fBClient\fP"

.PP
Represents a client that is being handled by howm\&. All the attributes that are needed by howm for a client are stored here\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
