.TH "workspace.h" 3 "Sun Nov 30 2014" "howm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
workspace.h \- 
.PP
howm  

.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <client\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBkill_ws\fP (const int ws)"
.br
.RI "\fIKills the given workspace\&. \fP"
.ti -1c
.RI "int \fBcorrect_ws\fP (unsigned int ws)"
.br
.RI "\fICorrectly wrap a workspace number\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
howm 


.PP
\fBAuthor:\fP
.RS 4
Harvey Hunt
.RE
.PP
\fBDate:\fP
.RS 4
2014 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int correct_ws (unsigned intws)"

.PP
Correctly wrap a workspace number\&. This prevents workspace numbers from being greater than WORKSPACES or less than 1\&.
.PP
\fBParameters:\fP
.RS 4
\fIws\fP The value that needs to be corrected\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A corrected workspace number\&. 
.RE
.PP

.SS "void kill_ws (const intws)"

.PP
Kills the given workspace\&. 
.PP
\fBParameters:\fP
.RS 4
\fIws\fP The workspace to be killed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for howm from the source code\&.
